import type { BlogPost } from "../types"

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "Getting Started with Next.js",
    subtitle: "Learn how to build modern web applications with Next.js",
    content: "Full content here...",
    image: "/placeholder.svg?height=400&width=600",
    createdAt: "2024-05-28T00:00:00Z",
    updatedAt: "2024-05-28T00:00:00Z",
    published: true,
    viewCount: 100,
    authorId: "author1",
    likes: [],
    author: {
      id: "author1",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "2",
    title: "Mastering Tailwind CSS",
    subtitle: "Discover how to create beautiful, responsive designs",
    content: "Full content here...",
    image: "/placeholder.svg?height=400&width=600",
    createdAt: "2024-05-25T00:00:00Z",
    updatedAt: "2024-05-25T00:00:00Z",
    published: true,
    viewCount: 75,
    authorId: "author2",
    likes: [],
    author: {
      id: "author2",
      name: "John Doe",
      email: "john.doe@example.com",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "3",
    title: "Server Components in React",
    subtitle: "Explore the power of React Server Components",
    content: "Full content here...",
    image: "/placeholder.svg?height=400&width=600",
    createdAt: "2024-05-22T00:00:00Z",
    updatedAt: "2024-05-22T00:00:00Z",
    published: true,
    viewCount: 150,
    authorId: "author3",
    likes: [],
    author: {
      id: "author3",
      name: "Alex Johnson",
      email: "alex.johnson@example.com",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "4",
    title: "Building a REST API with Node.js",
    subtitle: "Step-by-step guide to creating a robust REST API",
    content: "Full content here...",
    image: "/placeholder.svg?height=400&width=600",
    createdAt: "2024-05-20T00:00:00Z",
    updatedAt: "2024-05-20T00:00:00Z",
    published: true,
    viewCount: 90,
    authorId: "author4",
    likes: [],
    author: {
      id: "author4",
      name: "Sarah Williams",
      email: "sarah.williams@example.com",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "5",
    title: "Introduction to TypeScript",
    subtitle: "Why TypeScript is becoming the standard",
    content: "Full content here...",
    image: "/placeholder.svg?height=400&width=600",
    createdAt: "2024-05-18T00:00:00Z",
    updatedAt: "2024-05-18T00:00:00Z",
    published: true,
    viewCount: 120,
    authorId: "author5",
    likes: [],
    author: {
      id: "author5",
      name: "Mike Brown",
      email: "mike.brown@example.com",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "6",
    title: "Responsive Design Principles",
    subtitle: "Learn the key principles for creating websites",
    content: "Full content here...",
    image: "/placeholder.svg?height=400&width=600",
    createdAt: "2024-05-15T00:00:00Z",
    updatedAt: "2024-05-15T00:00:00Z",
    published: true,
    viewCount: 85,
    authorId: "author6",
    likes: [],
    author: {
      id: "author6",
      name: "Emily Chen",
      email: "emily.chen@example.com",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
]
