import type { BlogPost } from "./types"

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    title: "Getting Started with Next.js",
    slug: "getting-started-with-nextjs",
    excerpt: "Learn how to build modern web applications with Next.js, the React framework for production.",
    content: "Full content here...",
    coverImage: "/placeholder.svg?height=400&width=600",
    date: "May 28, 2024",
    readingTime: 5,
    categories: ["Development", "React", "Next.js"],
    author: {
      name: "Jane Smith",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "2",
    title: "Mastering Tailwind CSS",
    slug: "mastering-tailwind-css",
    excerpt: "Discover how to create beautiful, responsive designs with Tailwind CSS utility classes.",
    content: "Full content here...",
    coverImage: "/placeholder.svg?height=400&width=600",
    date: "May 25, 2024",
    readingTime: 7,
    categories: ["Design", "CSS", "Tailwind"],
    author: {
      name: "John Doe",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "3",
    title: "Server Components in React",
    slug: "server-components-in-react",
    excerpt: "Explore the power of React Server Components and how they improve performance.",
    content: "Full content here...",
    coverImage: "/placeholder.svg?height=400&width=600",
    date: "May 22, 2024",
    readingTime: 10,
    categories: ["Development", "React", "Performance"],
    author: {
      name: "Alex Johnson",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "4",
    title: "Building a REST API with Node.js",
    slug: "building-rest-api-nodejs",
    excerpt: "Step-by-step guide to creating a robust REST API using Node.js and Express.",
    content: "Full content here...",
    coverImage: "/placeholder.svg?height=400&width=600",
    date: "May 20, 2024",
    readingTime: 8,
    categories: ["Development", "Node.js", "API"],
    author: {
      name: "Sarah Williams",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "5",
    title: "Introduction to TypeScript",
    slug: "introduction-to-typescript",
    excerpt: "Why TypeScript is becoming the standard for large-scale JavaScript applications.",
    content: "Full content here...",
    coverImage: "/placeholder.svg?height=400&width=600",
    date: "May 18, 2024",
    readingTime: 6,
    categories: ["Development", "TypeScript", "JavaScript"],
    author: {
      name: "Mike Brown",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
  {
    id: "6",
    title: "Responsive Design Principles",
    slug: "responsive-design-principles",
    excerpt: "Learn the key principles for creating websites that work well on any device.",
    content: "Full content here...",
    coverImage: "/placeholder.svg?height=400&width=600",
    date: "May 15, 2024",
    readingTime: 5,
    categories: ["Design", "CSS", "Responsive"],
    author: {
      name: "Emily Chen",
      avatar: "/placeholder.svg?height=100&width=100",
    },
  },
]
